generator:
  class: sfDoctrineGenerator
  param:
    model_class:           TckCustom
    theme:                 jroller
    non_verbose_templates: true
    with_show:             false
    singular:              ~
    plural:                ~
    route_prefix:          tckCustom
    with_doctrine_route:   true
    actions_base_class:    sfActions


