indexSuccess:
  stylesheets: [grp-event-list]
  javascripts: [lists]
editSuccess:
  stylesheets: [gauge, grp-event: { media: all }, grp-professional]
  javascripts: [<?php if ( !sfConfig::get('app_options_remove_slow_js',false) ): ?>jquery.tablescroll.js<?php endif ?>]
gaugeSuccess:
  stylesheets: [gauge, grp-event]
newSuccess:
  stylesheets: [grp-professional]
  javascripts: [grp-professional]
