generator:
  class: sfDoctrineGenerator
  param:
    model_class:           Event
    theme:                 jroller
    non_verbose_templates: true
    with_show:             false
    singular:              ~
    plural:                ~
    route_prefix:          event
    with_doctrine_route:   true
    actions_base_class:    sfActions

    config:
      actions: ~
      fields:  ~
      list:
        display: [MetaEvent,=name]
        object_actions:
          _edit: ~
          _extract_accepted:
            name: Accepted
            action: accepted
            ui-icon: cart
          _extract_refused:
            name: Refused
            action: refused
            ui-icon: cancel
          _extract_impossible:
            name: Impossible
            action: impossible
            ui-icon: notice
          _export: 
            name: Export accepted
            action: export
            ui-icon: person
        batch_actions: {}
        title: By event
        table_method: getOnlyGroupEvents
        actions:
          _from_date_to_date:
            action: fromDateToDate
          _add_a_contact_to_an_event:
            action: addContactToEvent
          _add_a_manifestation_to_an_event:
            action: addManifestationToEvent
      filter:
        display: [meta_event_id, dates_range, name]
      form: ~
      edit:
        title: Entry %%name%%
        actions:
          _list: ~
          _print:
            action: print
            label: Print
      new:
        actions: { _list: ~ }
