generator:
  class: sfDoctrineGenerator
  param:
    model_class:           order
    theme:                 jroller
    non_verbose_templates: true
    with_show:             false
    singular:              ~
    plural:                ~
    route_prefix:          order
    with_doctrine_route:   true
    actions_base_class:    sfActions

    config:
      actions: ~
      fields:
        sf_guard_user_id: { label: User }
        cancel: { label: Del. }
        event_name: { label: Name }
        manifestation_happens_at: { label: Date, type: date }
        manifestations_list: { label: Manifestations }
        contact: { is_real: true }
      list:
        display: [_id,_transaction_id,_closed,_contact,_manifestations,_comment,created_at,User]
        table_method: doSelectIndex
        sort: [id, DESC]
        object_actions:
          _cancel:
            label: Delete
            ui-icon: trash
            action: cancel 
        batch_actions: {}
      filter:
        display:
          Transaction: [transaction_id, closed, created_at, has_confirmed_ticket, contact_id, organism_id, sf_guard_user_id]
          Manifestation: [event_name, manifestations_list, manifestation_happens_at, workspaces_list, meta_events_list]
      form:    ~
      edit:    ~
      new:     ~
