<?php

/**
 * TckCustomTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class TckCustomTable extends PluginTckCustomTable
{
    /**
     * Returns an instance of this class.
     *
     * @return object TckCustomTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('TckCustom');
    }
}