generator:
  class: sfDoctrineGenerator
  param:
    model_class:           Control
    theme:                 jroller
    non_verbose_templates: true
    with_show:             false
    singular:              ~
    plural:                ~
    route_prefix:          control
    with_doctrine_route:   true
    actions_base_class:    sfActions

    config:
      actions: ~
      fields:
        sf_guard_user_id: { label: User }
      list: 
        title: Statistics on ticket controls
        display: [User, Checkpoint, created_at]
        batch_actions:
          _exceptions:
            label: Create exceptions
        object_actions: []
        sort: [created_at, desc]
        table_method: createQuery
      filter:
        display: [sf_guard_user_id, checkpoint_id, created_at]
      form:    ~
      edit:    ~
      new:     ~
