csvSuccess:
  has_layout: false
  http_metas:
    content-type: text/comma-separated-values
    content-disposition: attachment; filename="stats-geo.csv"

jsonSuccess:
  has_layout: false
  http_metas:
    content-type: application/json
            
