<?php

/**
 * PluginTckCustomTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class PluginTckCustomTable extends TraceableTable
{
    /**
     * Returns an instance of this class.
     *
     * @return object PluginTckCustomTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('PluginTckCustom');
    }
}