all:
  credentials: [event-manif]

state:
  credentials: [[event-manif, tck-transaction]]
update:
  credentials: [event-manif-gauge]
edit:
  credentials: [event-manif-gauge]
new:
  credentials: [event-manif-gauge]
create:
  credentials: [event-manif-gauge]
delete:
  credentials: [event-manif-gauge]
batchDelete:
  credentials: [event-manif-gauge]
